# Possible values:
#  0: no-op
#  2: Mission Control (all windows)
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
- name: Set up Hotcorners
  block:
    - name: Set top-left
      block:
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-tl-corner
            type: int
            value: 6
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-tl-modifier
            type: int
            value: 0
    - name: Set top-right
      block:
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-tr-corner
            type: int
            value: 6
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-tr-modifier
            type: int
            value: 0
    - name: Set bottom-left
      block:
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-bl-corner
            type: int
            value: 6
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-bl-modifier
            type: int
            value: 0
    - name: Set bottom-right
      block:
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-br-corner
            type: int
            value: 6
        - community.general.system.osx_defaults:
            domain: com.apple.dock
            key: wvous-br-modifier
            type: int
            value: 0

- name: Set up Dock
  block:
    - name: Remove all icons from Dock
      community.general.system.osx_defaults:
        domain: com.apple.dock
        key: persistent-apps
        type: array
        value: []
    # Possible icon size: 16 - 128
    - name: Set icon size to 16
      community.general.system.osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: int
        value: 16

- name: Set up Mission Control
  block:
    - name: (Todo:)Disable auto rearrange workspaces
      community.general.system.osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: False

- name: Apply changes
  become: true
  shell: |
    killall Dock
